### ISSUE TITLE
설계상의 고민, Service layer 설계 시 Interface 화의 필요성?

### ISSUE THREAD

**Issue by JasonLee228** [CENT-PROJECT/CENT-BACKEND#3]
서비스 계층, Business Layer에 Interface를 만들어야 되는지에 대한 고민이 필요.

다형성 부분에서  설계와 구현을 일단 나누는 것 자체는 기본이라고 배우고는 있어요
근데 이게 꼭 나뉘어야 하는가? 라는 의문은 생각해보니 좀 들긴 하더라구요
그래서 좀 찾아봤더니 확장의 가능성이 0인가? 라는 생각은 좀 해봐야 할 것 같아요

**Comment by JasonLee228** [comment]
단순히 지금 만들고 있는 회원 가입, 유저, 팀 관련된 부분에서는 확장의 가능성이 없죠. 회원 가입하고 로그인하는데 더한 추상화가 필요할까 싶긴 해요

근데 우리 서비스의 목적을 먼저 파악하는게 중요하다고 생각합니다
지금 개발 중인 spoty라는 프로젝트는 축구로 끝나지 않아요 적어도 지금은요
조금만 더 나아가 생산될 알림 서비스라던지, 축구 이외의 서비스가 하나라도 들어가게 되는 순간, 확장성은 무조건 필요해집니다
그런 확장의 문제가 발생했을 때에 같은 팀, 및 여러가지 클래스를 재생산할지, 유지 보수 측면에서는 어떻게 될 지 생각이 먼저 필요하겠네요

**Comment by JasonLee228** [comment]
해당 이슈는 많은 사람들이 이미 고민중인 얘기기도 하네용

**Comment by JasonLee228** [comment]
@JIWEON-JEONG

**Comment by JIWEON-JEONG** [comment]
Service 레이어 에서도 인터페이스가 필요 할 수 있다고 생각합니다.

예를 들어 할인 정책을 적용한다고 하였을때, 이벤트기간동안은 할인정책1 을 사용하고, 평소에는 할인정책 2번을 사용하겠다. 
할인정책 이라는 인터페이스를 만들어 추상화의 이점을 볼수 있을거같습니다. 

하지만,  그렇다고 결제 서비스를 모두 인터페이스로 만드는 것. 둘중에 뭐가 더 최적화가 되어있냐? 라고 생각하면 
저는 전자가 더 최적화가 되어있다고 생각합니다.

추후 확장이 필요할경우, 그때 따로 해당 부분을 인터페이스로 추상화하여 버전업을 시키는 쪽으로 구현하는게 조금더 
리소스를 효율적으로 쓸수 있지 않을까 라는 생각입니다. 

현재 저희 서비스에서 Login 같은 경우 OAUTH 와 자체로그인 두가지 방식을 사용하고 있기 때문에 만약 
추상화를 도입한다면 이부분에서 대해서 추상화를 하여 구현하는 것이 UserService 전체의 서비스를 추상화 하는 것보다
불필요한 추상화를 줄일 수 있을거같습니다.

**Comment by JasonLee228** [comment]
결론적으론 현재 다형성을 도입하는 것보다 하나의 서비스 클래스만으로 구현하는 쪽으로 하고 싶다는 말씀이시죠?

**Comment by JIWEON-JEONG** [comment]
> 결론적으론 현재 다형성을 도입하는 것보다 하나의 서비스 클래스만으로 구현하는 쪽으로 하고 싶다는 말씀이시죠?

제 의견은 추상화를 하는것은 좋다고 생각하지만, 추후 확장 가능성이 있을때 추상화를 하는게 더 합리적이다 라는 의견이였습니다.
일단은 당장에 확장 가능성있는 추상화를 하는건 찬성입니다만, UserService 전체를 인터페이스 화 하는 것은 위 댓글과 같은 이유로 다형성이 필요한 부분이 있다면 그때 추상화 해보는건 어떨가요?

**Comment by JasonLee228** [comment]
전체적인 코드 구조의 통일화를 위해서 지금부터 하려는 생각이었는데, 지원님 의견대로 필요 시 리팩터링 하는 것도 나쁘지 않다고 생각합니다 :)

**Comment by JIWEON-JEONG** [comment]
그러면 추후 필요할때 리팩토링 으로 하시는게 어떨까요? 괜찮으시면 따봉 눌러주시면 그렇게 이해할게용
